/* ns7iii_map.h — Numark NS7III default MIDI map
 * Auto-included by djcmd.c — do not edit the compiled-in copy directly.
 * To customise, delete ~/.config/djcmd/ns7_iii.map and edit the regenerated file.
 *
 * Hardware overview:
 *   The NS7III has 2 physical platters but djcmd supports 4 virtual decks (A–D).
 *   Layer switching maps each platter to a different virtual deck:
 *
 *     LEFT  platter (MIDI ch2) — deck_sel [1] = Deck A (default)
 *                                deck_sel [3] = Deck C (layer 2)
 *     RIGHT platter (MIDI ch3) — deck_sel [2] = Deck B (default)
 *                                deck_sel [4] = Deck D (layer 2)
 *
 *   Press deck selector button [3] to switch the left platter to Deck C;
 *   press [1] to switch it back to Deck A.  Same for [4]/[2] on the right.
 *   Track playing on the previous deck continues unaffected — only new input
 *   routes to the newly selected deck.  Activate 4-deck mode in djcmd first
 *   (press T or use ESC → DISPLAY tab) before switching to Deck C or D.
 *
 * Motor channels (1-indexed):
 *   ch2 = left platter motor (Deck A / Deck C when layer 2 active)
 *   ch3 = right platter motor (Deck B / Deck D when layer 2 active)
 *   The motor_start/stop out bindings below reflect these channels.
 *
 * Display note (crossed configuration):
 *   Display Right ALSA card (dev_id=0x20) → Deck A (left platter)
 *   Display Left  ALSA card (dev_id=0x10) → Deck B (right platter)
 *   The two center displays face opposite platters (confirmed by pcap).
 */
#ifndef NS7III_MAP_H
#define NS7III_MAP_H

static const char NS7III_MAP[] =
	"# djcmd MIDI map — auto-generated\n"
	"# Input bindings:  action_name  status_hex  data1_dec\n"
	"# Output bindings: out  name  status_hex  data1_dec  data2_dec\n"
	"# Tuning params:   set  name  value\n"
	"# status: B0-BF=CC ch1-16  90-9F=NoteOn ch1-16  80-8F=NoteOff ch1-16\n"
	"#\n"
	"# Cross-reference notes (djcmd name → physical button → Mixxx name):\n"
	"#   reverse_a/b      91/92 note 63 (0x3F) = LOOP OUT button  → Mixxx: loopOutA/B\n"
	"#   motor_toggle_a/b 91/92 note 68 (0x44) = SLIP button       → Mixxx: slipA/B  (led_slip_a/b)\n"
	"#   pad_1_a..8_a    91    note 71-78      = PAD 1-8 deck A\n"
	"#   pad_1_b..8_b    92    note 71-78      = PAD 1-8 deck B\n"
	"#   pad_mode_cues_a/b    91/92 note 79 = CUES mode button\n"
	"#   pad_mode_autoroll_a/b 91/92 note 80 = AUTO/ROLL mode button\n"
	"#   param_left/right_a/b  91/92 note 69/70 = PARAMETER 1 left/right\n"
	"#   pitch_range_a/b  91/92 note 61 (0x3D) = SYNC button        → Mixxx: SHIFT+syncA/B cycles range\n"
	"#   led_deck_a/b     91/92 note 52 (0x34) = PLAY button LED    → same address as play_a/b input\n"
	"#   shift_a/b        91/92 note 53 (0x35) = SHIFT button\n"
	"#   cue_default_a/b  91/92 note 51 (0x33) = CUE button\n"
	"#   pitch_center_a/b 91/92 note 64 (0x40) = PITCH CENTER button\n"
	"#   cf_curve         B0 note 65 (0x41) = X-FADER CURVE knob\n"
	"#\n"
	"# EQ CC numbers (probed from hardware — used as authoritative source):\n"
	"#   Ch1 strip: low=9  mid=10 high=11   Ch2 strip: low=14 mid=15 high=16\n"
	"#   Ch3 strip: low=20 mid=21 high=22   Ch4 strip: low=25 mid=26 high=27\n"
	"# Strip physical order left→right: Ch3, Ch1, Ch2, Ch4\n"
	"#\n"
	"# Motor protocol note:\n"
	"#   Motor start/stop uses CC#65=127 (start) and CC#66=127 (stop) on ChN.\n"
	"#   Full sequence: CC#75=0 Ch1 (enable), CC#65=127 ChN (start), CC#68=1 ChN,\n"
	"#   then CC#73 ramp 0→100 over 18 steps at 20Hz + CC#74 sawtooth on Ch1.\n"
	"#   Stop: CC#73=0 ChN, CC#66=127 ChN, CC#68=0 ChN.\n"
	"#   CC#74 Ch1 doubles as the physical channel-1 VU meter level after ramp.\n"
	"#   The out motor_start/stop entries below mirror these CCs for reference.\n"
	"#\n"
	"# FX knob encoding:\n"
	"#   The NS7III FX knobs use center-64 relative CC encoding:\n"
	"#   data2 > 64 = clockwise (+), data2 < 64 = counter-clockwise (-), 64 = no motion.\n"
	"#   This is the same encoding as the jog wheel and library encoder.\n"
	"#   The CCs listed below are best-known values but unconfirmed by capture.\n"
	"#   If FX knobs behave incorrectly, use LEARN mode to re-bind them.\n"
	"#\n"
	"set  jog_type         ns7iii\n"
	"set  jog_scratch_revs 80182\n"
	"set  jog_ref_delta    0.0078125\n"
	"set  jog_motor_dead   0.1500\n"
	"set  jog_vel_max      10.0\n"
	"set  jog_smooth  0.080\n"
	"set  jog_dead    0.0800\n"
	"set  jog_spike   0.750\n"
	"set  jog_slew    0.0300\n"
	"set  jog_settle  2000\n"
	"#\n"
	"jog_spin_a          B1    0\n"
	"jog_pb_a            E1    0\n"
	"jog_spin_b          B2    0\n"
	"jog_pb_b            E2    0\n"
	"vol_a               B0    8\n"
	"vol_b               B0   13\n"
	"vol_c               B0   19\n"
	"vol_d               B0   24\n"
	"eq_low_a            B0    9\n"
	"eq_low_b            B0   14\n"
	"eq_low_c            B0   20\n"
	"eq_low_d            B0   25\n"
	"eq_mid_a            B0   10\n"
	"eq_mid_b            B0   15\n"
	"eq_mid_c            B0   21\n"
	"eq_mid_d            B0   26\n"
	"eq_high_a           B0   11\n"
	"eq_high_b           B0   16\n"
	"eq_high_c           B0   22\n"
	"eq_high_d           B0   27\n"
	"filter_a            B0   91\n"
	"filter_b            B0   92\n"
	"filter_c            B0   90\n"
	"filter_d            B0   93\n"
	"crossfader          B0    7\n"
	"cf_curve            B0   65\n"
	"master_vol          B0   66\n"
	"booth_vol           B0   67\n"
	"gain_a              B0   12\n"
	"gain_b              B0   17\n"
	"gain_c              B0   23\n"
	"gain_d              B0   28\n"
	"strip_a             B1    2\n"
	"strip_b             B2    2\n"
	"shift_a             91   53\n"
	"cue_default_a       91   51\n"
	"pitch_center_a      91   64\n"
	"play_a              91   52\n"
	"play_b              92   52\n"
	"play_c              93   52\n"
	"play_d              94   52\n"
	"cue_default_a       91   51\n"
	"cue_default_b       92   51\n"
	"cue_default_c       93   51\n"
	"cue_default_d       94   51\n"
	"reverse_a           91   63\n"
	"reverse_b           92   63\n"
	"reverse_c           93   63\n"
	"reverse_d           94   63\n"
	"pitch_range_a       91   61\n"
	"pitch_range_b       92   61\n"
	"pitch_range_c       93   61\n"
	"pitch_range_d       94   61\n"
	"motor_toggle_a      91   68\n"
	"motor_toggle_b      92   68\n"
	"motor_toggle_c      93   68\n"
	"motor_toggle_d      94   68\n"
	"tap_bpm_a           91   10\n"
	"tap_bpm_b           92   10\n"
	"pitch_a             B1    1\n"
	"pitch_b             B2    1\n"
	"pitch_c             B3    1\n"
	"pitch_d             B4    1\n"
	"pitch_lsb_a         B1   33\n"
	"pitch_lsb_b         B2   33\n"
	"pitch_lsb_c         B3   33\n"
	"pitch_lsb_d         B4   33\n"
	"jog_spin_a          B1    0\n"
	"jog_spin_b          B2    0\n"
	"jog_spin_c          B3    0\n"
	"jog_spin_d          B4    0\n"
	"jog_pb_a            E1    0\n"
	"jog_pb_b            E2    0\n"
	"jog_pb_c            E3    0\n"
	"jog_pb_d            E4    0\n"
	"jog_touch_a         91   62\n"
	"jog_touch_b         92   62\n"
	"jog_touch_c         93   62\n"
	"jog_touch_d         94   62\n"
	"# Pads 1-8 deck A (ch2, notes 0x47-0x4E = 71-78)\n"
	"pad_1_a             91   71\n"
	"pad_2_a             91   72\n"
	"pad_3_a             91   73\n"
	"pad_4_a             91   74\n"
	"pad_5_a             91   75\n"
	"pad_6_a             91   76\n"
	"pad_7_a             91   77\n"
	"pad_8_a             91   78\n"
	"# Pads 1-8 deck B (ch3, notes 0x47-0x4E = 71-78)\n"
	"pad_1_b             92   71\n"
	"pad_2_b             92   72\n"
	"pad_3_b             92   73\n"
	"pad_4_b             92   74\n"
	"pad_5_b             92   75\n"
	"pad_6_b             92   76\n"
	"pad_7_b             92   77\n"
	"pad_8_b             92   78\n"
	"# Pad mode buttons deck A (ch2)\n"
	"pad_mode_cues_a     91   79\n"
	"pad_mode_autoroll_a 91   80\n"
	"# Pad mode buttons deck B (ch3)\n"
	"pad_mode_cues_b     92   79\n"
	"pad_mode_autoroll_b 92   80\n"
	"# Parameter 1 left/right (loop size control in autoloop/roll modes)\n"
	"param_left_a        91   69\n"
	"param_right_a       91   70\n"
	"param_left_b        92   69\n"
	"param_right_b       92   70\n"
	"# FX buttons deck A (ch1 global notes): btn1=slot0 btn2=slot1 btn3=master\n"
	"fx_btn_1_a          90   15\n"
	"fx_btn_2_a          90   16\n"
	"fx_btn_3_a          90   18\n"
	"# FX buttons deck B (ch1 global notes)\n"
	"fx_btn_1_b          90   19\n"
	"fx_btn_2_b          90   20\n"
	"fx_btn_3_b          90   22\n"
	"# FX knobs deck A (ch2, 2's-complement relative: 1-63=CW, 64-127=CCW)\n"
	"# CCs unconfirmed — use LEARN mode if these don't respond correctly\n"
	"fx_knob_1_a         B1    4\n"
	"fx_knob_2_a         B1    5\n"
	"fx_knob_3_a         B1    6\n"
	"# FX wet/dry knob deck A (ch2, 2's-complement relative)\n"
	"fx_wet_a            B1   72\n"
	"# FX knobs deck B (ch3, 2's-complement relative: 1-63=CW, 64-127=CCW)\n"
	"# CCs unconfirmed — use LEARN mode if these don't respond correctly\n"
	"fx_knob_1_b         B2   73\n"
	"fx_knob_2_b         B2   74\n"
	"fx_knob_3_b         B2   75\n"
	"# FX wet/dry knob deck B (ch3, 2's-complement relative)\n"
	"fx_wet_b            B2   76\n"
	"# FX button LED outputs (ch1, same notes as input — light when effect active)\n"
	"out  led_fx_btn_1_a      90   15  127\n"
	"out  led_fx_btn_2_a      90   16  127\n"
	"out  led_fx_btn_3_a      90   18  127\n"
	"out  led_fx_btn_1_b      90   19  127\n"
	"out  led_fx_btn_2_b      90   20  127\n"
	"out  led_fx_btn_3_b      90   22  127\n"
	"deck_sel_1          90    2\n"
	"deck_sel_2          90    3\n"
	"deck_sel_3          90    4\n"
	"deck_sel_4          90    5\n"
	"lib_encoder         B0    3\n"
	"lib_select          90    8\n"
	"lib_back            90    6\n"
	"lib_fwd             90    7\n"
	"lib_load_a          91   49\n"
	"lib_load_b          92   49\n"
	"lib_load_c          93   49\n"
	"lib_load_d          94   49\n"
	"panel_files         90    9\n"
	"panel_library       90   11\n"
	"pitch_a             B1    1\n"
	"pitch_b             B2    1\n"
	"shift_b             92   53\n"
	"cue_default_b       92   51\n"
	"pitch_center_b      92   64\n"
	"play_b              92   52\n"
	"nudge_fwd           91   60\n"
	"nudge_back          91   59\n"
	"nudge_fwd_b         92   60\n"
	"nudge_back_b        92   59\n"
	"# Bleep (momentary slip+reverse): LOOP OUT button on each platter side\n"
	"# Note On = engage reverse+save pos, Note Off = restore pos+forward\n"
	"bleep_a             91   62\n"
	"bleep_b             92   62\n"
	"# Manual loop pad mode: LOOP button on each platter side (note 81)\n"
	"pad_mode_manual_a   91   81\n"
	"pad_mode_manual_b   92   81\n"
	"# Filter toggle buttons (ch1 global notes, one per hardware channel)\n"
	"# Deck A (Ch1/strip left)  = note 35, Deck B (Ch2/strip right) = note 37\n"
	"filter_toggle_a     90   35\n"
	"filter_toggle_b     90   37\n"
	"# 14-bit pitch fader LSB — CC#33 same channel as pitch MSB (CC#1)\n"
	"# Bind these to get ~0.05 cent resolution vs. ~0.7 cent at 7-bit\n"
	"pitch_lsb_a         B1   33\n"
	"pitch_lsb_b         B2   33\n"
	"\n"
	"# Output bindings (djcmd → controller)\n"
	"# motor_start/stop: CC#65=127 start, CC#66=127 stop, per-deck channel.\n"
	"# These match what motor_set() sends directly in code.\n"
	"out  motor_start_a       B1   65  127\n"
	"out  motor_stop_a        B1   66  127\n"
	"out  motor_start_b       B2   65  127\n"
	"out  motor_stop_b        B2   66  127\n"
	"out  led_cue_default_a   91   51  127\n"
	"out  led_deck_a          91   52  127\n"
	"out  led_cue_default_b   92   51  127\n"
	"out  led_deck_b          92   52  127\n"
	"out  led_deck_1          90    2  127\n"
	"out  led_deck_2          90    3  127\n"
	"out  led_deck_3          90    4  127\n"
	"out  led_deck_4          90    5  127\n"
	"out  led_sync_a          91   61  127\n"
	"out  led_sync_b          92   61  127\n"
	"out  led_slip_a          91   68  127\n"
	"out  led_slip_b          92   68  127\n"
	"out  led_loop_a          91   65  127\n"
	"out  led_loop_b          92   65  127\n"
	"out  led_pitch_center_a  91   64  127\n"
	"out  led_pitch_center_b  92   64  127\n"
	"# Pad/cue LED outputs (velocity = colour; djcmd sets colour per cue/mode)\n"
	"out  led_cue_1_a         91   71  127\n"
	"out  led_cue_2_a         91   72  127\n"
	"out  led_cue_3_a         91   73  127\n"
	"out  led_cue_4_a         91   74  127\n"
	"out  led_cue_5_a         91   75  127\n"
	"out  led_cue_6_a         91   76  127\n"
	"out  led_cue_7_a         91   77  127\n"
	"out  led_cue_8_a         91   78  127\n"
	"out  led_cue_1_b         92   71  127\n"
	"out  led_cue_2_b         92   72  127\n"
	"out  led_cue_3_b         92   73  127\n"
	"out  led_cue_4_b         92   74  127\n"
	"out  led_cue_5_b         92   75  127\n"
	"out  led_cue_6_b         92   76  127\n"
	"out  led_cue_7_b         92   77  127\n"
	"out  led_cue_8_b         92   78  127\n"
	"out  led_pad_hotcue_a    91   79  127\n"
	"out  led_pad_roll_a      91   80  127\n"
	"out  led_pad_loop_a      91   81  127\n"
	"out  led_pad_sampler_a   91   82  127\n"
	"out  led_pad_slicer_a    91   83  127\n"
	"out  led_pad_hotcue_b    92   79  127\n"
	"out  led_pad_roll_b      92   80  127\n"
	"out  led_pad_loop_b      92   81  127\n"
	"out  led_pad_sampler_b   92   82  127\n"
	"out  led_pad_slicer_b    92   83  127\n"
	"# Filter toggle LEDs — same note as filter_toggle_a/b inputs\n"
	"out  led_filter_a        90   35  127\n"
	"out  led_filter_b        90   37  127\n";

#endif /* NS7III_MAP_H */
